### ISSUE TITLE
Tag and release

### ISSUE THREAD

**Issue by bignose-debian** [erkyrath/glk-dev#1]
Does the `Glulx-Spec-Changes` file constitute a change log for this code base?

If so, please create GnuPG-signed tags for the commits that represent each version mentioned: `3.0.0`, `3.1.0`, `3.1.1`, `3.1.2`, `3.1.3`. This allows understanding the state of the code base referred to by each version, by getting the code from the VCS by that tag.

If you could also create a “release” for each of those tags, that would be helpful too (GitHub will automatically make tarballs available with the correct name for each release).

**Comment by erkyrath** [comment]
This repository is a grab-bag of related projects and doesn't follow any particular release process. I keep both the Glk and Glulx specs in here, for example, along with various other bits of code.

Yes, it would be tidier for each spec to have its own repository and release history, but I haven't done that.

**Comment by bignose-debian** [comment]
My concern at the moment is for the programs in `dispatch_dump`, as a build dependency for `infglk.h`.

What's needed is to know “to generate `infglk.h` as expected, you need version 5.7.9 of `dispatch_dump`”. So versioned releases of at least `dispatch_dump` is what I'm seeking.

Which would be better: tracking versions and releasing in this repository, or splitting `dispatch_dump` to a separate repository for that code with versioned releases? I can open an issue for whichever of those is more feasible.

**Comment by erkyrath** [comment]
At present you should treat infglk.h as a static file and not try to generate it in other packages.

**Comment by bignose-debian** [comment]
On 17-Apr-2016, Andrew Plotkin wrote:
> At present you should treat infglk.h as a static file and not try to
> generate it in other packages.

So, the software in ‘dispatch_dump’ is what I'm trying to use. Should
I not use that software, to generate ‘infglk.h’?

-- 
 \     “We are all agreed that your theory is crazy. The question that |
  `\      divides us is whether it is crazy enough to have a chance of |
_o__)            being correct.” —Niels Bohr (to Wolfgang Pauli), 1958 |
Ben Finney <ben@benfinney.id.au>
