### ISSUE TITLE
blorbtool os.rename error on Windows

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glk-dev#2]
On Windows [os.rename can't rename to an existing file name](https://docs.python.org/2/library/os.html#os.rename). If the user has requested to overwrite the file (or is using -f) then can this be worked around?

I also noted that it didn't run using Python 3, but I didn't look to see how complicated it would be to make it run on it. Is it common to have python scripts that run in both python 2 and 3? It would be great if we could point to this tool with the greatest pre-req being "install (any version of) python" - which would only be required for Windows, because python comes on osx and should be installed on every distribution of linux (and if it isn't then any user of such a distribution would surely be competent enough to handle that themselves.)

**Comment by erkyrath** [comment]
Grr. Well, good to know.

Yes, it's common to have Python scripts that run in both 2 and 3. I haven't looked into what would be needed for this particular case. The rename thing is itself trouble: os.replace() exists only in Py3.3 and up.

**Comment by curiousdannii** [comment]
The output file could just be deleted if it already exists, couldn't it?

**Comment by erkyrath** [comment]
The point is to change the contents of the file with an atomic operation. rename() is a reliable way to do this on Unix (as long as the files are on the same filesystem).

I realize it's not really critical for this program.

**Comment by erkyrath** [comment]
Done.
